/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
export type CategoryFragment = {
    id: string;
    name: string;
    slug: string;
    file: ({
        url: string;
    }) | null;
    products: ({
        id: string;
        slug: string;
        name: string;
        description: string | null;
        price: number;
        assets: ({
            url: string;
        })[];
    })[];
};
export type Categories = {
    categories: (CategoryFragment)[];
};
export type CategoriesVariables = {};
