/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
export type CategoryFragment = {
    id: string;
    name: string;
    slug: string;
    file: ({
        url: string;
    }) | null;
};
export type Category = {
    category: (CategoryFragment) | null;
};
export type CategoryVariables = {
    slug: string;
};
