/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
export type ColorsFragment = {
    id: string;
    name: string;
    color: "fabric" | "gold_oak" | "silver_natural_oak" | "bronze_walnut" | "light_oak_wood" | "oak_wood" | "natural_aluminium" | "infantry_green" | "purple_heart" | "black_aluminium" | "brass_tone_aluminium" | "black_fabric" | "bronze_tone_aluminium" | "gold_tone" | "black" | "nordic_ice" | "white_marble" | "silver" | "gold" | "bronze" | "natural" | "grey_mist" | "green" | "black_anthracite" | "pink" | "anthracite_oxygen" | "berluti_edition" | "oxygen_blue" | "sand" | "dark_maroon" | "timber" | "navy" | "chestnut" | "parisian_night_blue";
    colorCode: {
        hex: any;
    };
    __typename: "ProductColor";
};
