/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
export type FrameColorsFragment = {
    id: string;
    name: string;
    frameColor: "silver" | "black" | "gold";
    colorCode: {
        hex: any;
    };
};
