/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
export type FrameColorsFragment = {
  id: string;
  name: string;
  frameColor: 'black' | 'gold' | 'silver';
  colorCode: {
    hex: any;
  };
  __typename: 'ProductFrameColor';
};
