/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
export type InstallationFragment = {
    id: string;
    description: string;
    image: {
        url: string;
    };
};
export type Installations = {
    installations: (InstallationFragment)[];
};
export type InstallationsVariables = {};
