/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
export type PositionningsFragment = {
    id: string;
    name: string;
    positionning: "fixed" | "motorized" | "wall_mount" | "floor" | "table";
    __typename: "ProductPositionning";
};
