/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
export type PositionningsFragment = {
  id: string;
  name: string;
  positionning: 'fixed' | 'floor' | 'motorized' | 'table' | 'wall_mount';
  __typename: 'ProductPositionning';
};
