/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
export type Settings = {
    settings: ({
        title: string | null;
        logo: ({
            url: string;
        }) | null;
    })[];
};
export type SettingsVariables = {};
