/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
export type Shops = {
    shops: ({
        id: string;
        name: string;
        address: string;
        city: string;
        country: string;
        stage: "DRAFT" | "PUBLISHED";
    })[];
};
export type ShopsVariables = {};
