/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
export type ShopFragment = {
    id: string;
    name: string;
    address: string;
    city: string;
    postalCode: string;
    country: string;
    phoneNumber: string;
    location: {
        latitude: number;
        longitude: number;
    };
    image: ({
        id: string;
        url: string;
    }) | null;
};
