/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
export type SlideshowAssetFragment = {
    id: string;
    alt: string;
    asset: {
        id: string;
        url: string;
    };
};
