/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
export type SoundbarColorsFragment = {
  id: string;
  name: string;
  color: 'grey_melange' | 'light_oak' | 'smocked_oak' | 'walnut';
  colorCode: {
    hex: any;
  };
  __typename: 'ProductSoundbarColor';
};
