/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
export type AssetsByProductVariantFragment = {
  id: string;
  asset: {
    url: string;
  }[];
  color:
    | (
        | 'fabric'
        | 'gold_oak'
        | 'silver_natural_oak'
        | 'bronze_walnut'
        | 'light_oak_wood'
        | 'oak_wood'
        | 'natural_aluminium'
        | 'infantry_green'
        | 'purple_heart'
        | 'black_aluminium'
        | 'brass_tone_aluminium'
        | 'black_fabric'
        | 'bronze_tone_aluminium'
        | 'gold_tone'
        | 'black'
        | 'nordic_ice'
        | 'white_marble'
        | 'silver'
        | 'gold'
        | 'bronze'
        | 'natural'
        | 'grey_mist'
        | 'green'
        | 'black_anthracite'
        | 'pink'
        | 'anthracite_oxygen'
        | 'berluti_edition'
        | 'oxygen_blue'
        | 'sand'
        | 'dark_maroon'
        | 'timber'
        | 'navy'
        | 'chestnut'
        | 'parisian_night_blue'
      )
    | null;
  positionning:
    | ('fixed' | 'motorized' | 'wall_mount' | 'floor' | 'table')
    | null;
  soundbarColor:
    | ('light_oak' | 'smocked_oak' | 'walnut' | 'grey_melange')
    | null;
  size: ('s_65' | 's_77' | 's_88' | 's_55' | 's_48') | null;
  frameColor: ('silver' | 'black' | 'gold') | null;
  supportColor: ('silver' | 'bronze' | 'piano_black') | null;
};
