/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
export type AssetsByProductVariantFragment = {
  id: string;
  asset: {
    url: string;
  }[];
  color:
    | (
        | 'anthracite_oxygen'
        | 'berluti_edition'
        | 'black'
        | 'black_aluminium'
        | 'black_anthracite'
        | 'black_fabric'
        | 'brass_tone_aluminium'
        | 'bronze'
        | 'bronze_tone_aluminium'
        | 'bronze_walnut'
        | 'chestnut'
        | 'dark_maroon'
        | 'fabric'
        | 'gold'
        | 'gold_oak'
        | 'gold_tone'
        | 'green'
        | 'grey_mist'
        | 'infantry_green'
        | 'light_oak_wood'
        | 'natural'
        | 'natural_aluminium'
        | 'navy'
        | 'nordic_ice'
        | 'oak_wood'
        | 'oxygen_blue'
        | 'parisian_night_blue'
        | 'pink'
        | 'purple_heart'
        | 'sand'
        | 'silver'
        | 'silver_natural_oak'
        | 'timber'
        | 'white_marble'
      )
    | null;
  positionning:
    | ('fixed' | 'floor' | 'motorized' | 'table' | 'wall_mount')
    | null;
  soundbarColor:
    | ('grey_melange' | 'light_oak' | 'smocked_oak' | 'walnut')
    | null;
  size: ('s_48' | 's_55' | 's_65' | 's_77' | 's_88') | null;
  frameColor: ('black' | 'gold' | 'silver') | null;
  supportColor: ('bronze' | 'piano_black' | 'silver') | null;
};
