/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
export type ColorsFragment = {
  id: string;
  name: string;
  color:
    | 'anthracite_oxygen'
    | 'berluti_edition'
    | 'black'
    | 'black_aluminium'
    | 'black_anthracite'
    | 'black_fabric'
    | 'brass_tone_aluminium'
    | 'bronze'
    | 'bronze_tone_aluminium'
    | 'bronze_walnut'
    | 'chestnut'
    | 'dark_maroon'
    | 'fabric'
    | 'gold'
    | 'gold_oak'
    | 'gold_tone'
    | 'green'
    | 'grey_mist'
    | 'infantry_green'
    | 'light_oak_wood'
    | 'natural'
    | 'natural_aluminium'
    | 'navy'
    | 'nordic_ice'
    | 'oak_wood'
    | 'oxygen_blue'
    | 'parisian_night_blue'
    | 'pink'
    | 'purple_heart'
    | 'sand'
    | 'silver'
    | 'silver_natural_oak'
    | 'timber'
    | 'white_marble';
  colorCode: {
    hex: any;
  };
  __typename: 'ProductColor';
};
