/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
export type InstallationFragment = {
  id: string;
  title: string;
  description: string;
  images: {
    url: string;
  }[];
};
