/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
export type LegalFragment = {
  privacyPolicy: string | null;
  legalNotice: string | null;
};
export type Legal = {
  legals: LegalFragment[];
};
export type LegalVariables = {};
