/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
export type PageFragment = {
  id: string;
  name: string;
  pageType: 'Page' | 'Home' | 'Categories';
  title: string | null;
  url: string;
};
