/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
export type SettingFragment = {
  title: string | null;
  logo: {
    url: string;
  } | null;
};
export type Settings = {
  settings: SettingFragment[];
};
export type SettingsVariables = {};
