/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
export type ShopFragment = {
  id: string;
  name: string;
  email: string | null;
  address: string;
  city: string;
  postalCode: string;
  country: string;
  phoneNumber: string;
  googleMapsUrl: string | null;
  image: {
    id: string;
    url: string;
  } | null;
  openHours: any | null;
};
export type Shops = {
  shops: ShopFragment[];
};
export type ShopsVariables = {};
