/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
export type SizesFragment = {
  id: string;
  name: string;
  size: 's_65' | 's_77' | 's_88' | 's_55' | 's_48';
  __typename: 'ProductSize';
};
