/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
export type SupportColorsFragment = {
  id: string;
  name: string;
  supportColor: 'silver' | 'bronze' | 'piano_black';
  colorCode: {
    hex: any;
  };
  __typename: 'ProductSupportColor';
};
